clc;
clear;
close all;

%% =========================================================
%  ADAS REALISTIC HUD - STEP 14
% ==========================================================

%% 1. VIDEO
videoFile = "C:/Users/musha/OneDrive/Desktop/ADAS_MTech_Project/resources/caltech_cordova1.avi";

video = VideoReader(videoFile);

%% 2. LOAD PRETRAINED LANENET
laneNetFile = matlab.internal.examples.downloadSupportFile( ...
    'gpucoder/cnn_models/lane_detection', ...
    'trainedLaneNet.mat');

load(laneNetFile);

%% 3. CALTECH CAMERA MODEL

focalLength = [309.4362 344.2161];
principalPoint = [318.9034 257.5352];
imageSize = [480 640];

camIntrinsics = cameraIntrinsics( ...
    focalLength, ...
    principalPoint, ...
    imageSize);

sensor = monoCamera( ...
    camIntrinsics, ...
    2.1798, ...
    'Pitch',14);

%% 4. LANENET STATISTICS

laneCoeffMeans = ...
    [-0.0002 0.0002 1.4740 ...
     -0.0002 0.0045 -1.3787];

laneCoeffStds = ...
    [0.0030 0.0766 0.6313 ...
     0.0026 0.0736 0.9846];

%% 5. VEHICLE INFORMATION

vehicleType = "CAR";

vehicleSpeed = 40;       % km/h

%% 6. READ ONE FRAME

frame = readFrame(video);

%% 7. NETWORK INPUT

inputImage = imresize(frame,[227 227]);

%% 8. LANE PREDICTION

outputs = predict(laneNet,inputImage);

%% 9. CONVERT OUTPUT

params = outputs .* laneCoeffStds + laneCoeffMeans;

%% 10. CREATE LANE BOUNDARIES

leftBoundary = parabolicLaneBoundary(params(1:3));

rightBoundary = parabolicLaneBoundary(params(4:6));

%% 11. DRAW DETECTED LANES

laneImage = insertLaneBoundary( ...
    frame, ...
    [leftBoundary rightBoundary], ...
    sensor, ...
    3:30, ...
    'Color','green', ...
    'LineWidth',4);

%% =========================================================
% 12. ADAS HUD
% ==========================================================

% Image dimensions

imageHeight = size(laneImage,1);
imageWidth  = size(laneImage,2);

%% 13. TOP STATUS BAR

laneImage = insertShape( ...
    laneImage, ...
    "FilledRectangle", ...
    [0 0 imageWidth 75], ...
    "Color","black", ...
    "Opacity",0.65);

%% 14. ADAS ACTIVE

laneImage = insertText( ...
    laneImage, ...
    [25 18], ...
    "ADAS ACTIVE", ...
    "FontSize",28, ...
    "TextColor","green", ...
    "BoxOpacity",0);

%% 15. SPEED

speedText = sprintf("%.0f km/h",vehicleSpeed);

laneImage = insertText( ...
    laneImage, ...
    [imageWidth-210 18], ...
    speedText, ...
    "FontSize",28, ...
    "TextColor","white", ...
    "BoxOpacity",0);

%% 16. VEHICLE TYPE

laneImage = insertText( ...
    laneImage, ...
    [25 imageHeight-125], ...
    "VEHICLE: CAR", ...
    "FontSize",22, ...
    "TextColor","white", ...
    "TextBoxColor","black", ...
    "BoxOpacity",0.65);

%% 17. CURRENT LANE

laneImage = insertText( ...
    laneImage, ...
    [25 imageHeight-85], ...
    "CURRENT: EGO LANE", ...
    "FontSize",22, ...
    "TextColor","white", ...
    "TextBoxColor","black", ...
    "BoxOpacity",0.65);

%% 18. RECOMMENDATION

recommendedLane = "LEFT";

laneImage = insertText( ...
    laneImage, ...
    [imageWidth-330 imageHeight-125], ...
    "RECOMMEND: LEFT", ...
    "FontSize",22, ...
    "TextColor","yellow", ...
    "TextBoxColor","black", ...
    "BoxOpacity",0.65);

%% 19. ADAS WARNING

laneImage = insertShape( ...
    laneImage, ...
    "FilledRectangle", ...
    [imageWidth-370 imageHeight-75 345 55], ...
    "Color","yellow", ...
    "Opacity",0.85);

laneImage = insertText( ...
    laneImage, ...
    [imageWidth-350 imageHeight-68], ...
    "LANE CHANGE ADVISED", ...
    "FontSize",20, ...
    "TextColor","black", ...
    "BoxOpacity",0);

%% 20. VEHICLE CENTER MARKER

vehicleCenterX = imageWidth/2;

laneImage = insertShape( ...
    laneImage, ...
    "Line", ...
    [vehicleCenterX imageHeight-180 ...
     vehicleCenterX imageHeight-110], ...
    "Color","red", ...
    "LineWidth",4);

%% 21. DISPLAY

figure;

imshow(laneImage);

title("ADAS Driver Assistance System");
